### ISSUE TITLE
Styling of container

### ISSUE THREAD

**Issue by linnhk** [RadKod/v-dropdown-menu#27]
Hi! 

I would love to be able to style the container of the dropdown menu. Specifically, I would like to change the default CSS for `min-width`. Would it be an option for you to maybe add a property for us to set specific CSS classes for the container?

**Comment by selimdoyranli** [comment]
Hi,

sorry for late reply. Did you look at the demo (https://v-dropdown-menu.now.sh/)

you can apply custom style to the dropdown-menu. bind a class to the v-dropdown-menu component then write your style

ex.

```
.v-dropdown-menu {
  $this: &;
  &.custom-style & {
    &__container {
      min-width: 400px;
...
```

....

**Comment by selimdoyranli** [comment]
> Hi!
> 
> I would love to be able to style the container of the dropdown menu. Specifically, I would like to change the default CSS for `min-width`. Would it be an option for you to maybe add a property for us to set specific CSS classes for the container?

Hi,

sorry for late reply. Did you look at the demo (https://v-dropdown-menu.now.sh/)

you can apply custom style to the dropdown-menu. bind a class to the v-dropdown-menu component then write your style

ex.

```
.v-dropdown-menu {
  $this: &;
  &.custom-style & {
    &__container {
      min-width: 400px;
...
```

**Comment by linnhk** [comment]
Ah, I see. No, I expected to find that kind of information in the README/documentation area. You might want to consider doing that. Thank you for the reply though! That was helpful.
