### ISSUE TITLE
"withDropdownCloser" doesn't work

### ISSUE THREAD

**Issue by linnhk** [RadKod/v-dropdown-menu#28]
Hi again there.

I'm using Pug in my Vue project, and here is a snippet where I'm trying to use the `withDropdownCloser` property. I can simply not make it work. The dropdown won't close when I click on the `router-link` "Account".

```pug
dropdown-menu(direction="right" :overlay="false")
    span(slot="trigger") User
    .user-dropdown(slot="body")
        router-link.submenu-user(to="/account" :withDropdownCloser="true") Account
        span.submenu-user(@click="logout") Sign Out
```

Am I doing something terribly wrong here?

**Comment by selimdoyranli** [comment]
> Hi again there.
> 
> I'm using Pug in my Vue project, and here is a snippet where I'm trying to use the `withDropdownCloser` property. I can simply not make it work. The dropdown won't close when I click on the `router-link` "Account".
> 
> ```
> dropdown-menu(direction="right" :overlay="false")
>     span(slot="trigger") User
>     .user-dropdown(slot="body")
>         router-link.submenu-user(to="/account" :withDropdownCloser="true") Account
>         span.submenu-user(@click="logout") Sign Out
> ```
> 
> Am I doing something terribly wrong here?

Hi,

sory for late reply.

please try this.

```
dropdown-menu(direction="right" :overlay="false" withDropdownCloser)
    span(slot="trigger") User
     .user-dropdown(slot="body")
          router-link.submenu-user(to="/account") Account
          span.submenu-user(@click="logout" dropdown-closer) Sign Out
```
