### ISSUE TITLE
isOpen prop is ignored

### ISSUE THREAD

**Issue by ventralnet** [RadKod/v-dropdown-menu#29]
I would like to be able to programatically open and close to dropdown through a prop.  It looks like there was an intension to be able to do this with the isOpen prop but there doesn't seem to be a watch in v-dropdown-menu on this prop.

A couple things need to  happen to have this work.  Add a 'none' mode so internally events won't be listened to and then add a watch for isOpen to open and close the drop down upon request

**Comment by TonyFresneau** [comment]
+1

**Comment by selimdoyranli** [comment]
Thanks for suggestion.

Fixed on version 1.3.2 (#30 )

Please check demo : https://v-dropdown-menu.now.sh
